### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by tpoisot** [tpoisot/ScientificComputingForTheRestOfUs#1]
# September

- [x] README update
- [x] Draft the roadmap and tag @philippbayer
- [x] Community guidelines (#3)
- [x] Figure out the mechanisms for contribution (`CONTRIBUTING`)

# October

- [x]  Script for the demo **Wed. 12** (#5)
- [x] Lesson 1 (Introduction to notebooks)
- [x] Ease of use of JuliaBox (#2) 
- [x]  Keep notebooks tidy on github (#4)
- [x] Ask feedback from targeted people

# November

- [x] Communication channel - [Gitter][gt]
- [x] Revise plan during MozillaFoundation/mozfest-program-2017/issues/180
- [x] Harvest comments from the MozFest session (#11)
- [x] Detailed plan for 4 (or 5) lessons
- [x] Ask feedback from Carpentries mailing list + community

[gt]: https://gitter.im/ScientificComputingForTheRestOfUs/Lobby

# December

- [x] Lesson 2 - flow
- [x] Lesson 3 - modular code

# January

- [x] Use the lessons in the classroom (BIO6032)

# February

- [ ] Open issues with needed edits
- [ ] Reality-check the estimated times
- [ ] Re-word objectives using Bloom's taxonomy (#14)

# May

- [x] Use the revised lessons during the summer school (BIO6035)
 
# June

- [ ] Lesson 4 - testing
- [ ] Lesson 5 - debugging

# July

- [ ] Capstone - break, next, continue
- [ ] Capstone - map, filter, reduce
- [ ] Capstone - parallel computing

**Comment by philippbayer** [comment]
🎆 👍

**Comment by tpoisot** [comment]
Tagging @dasaderi 🦊

**Comment by tpoisot** [comment]
Also tagging @trallard 🦊

**Comment by trallard** [comment]
🤜🏼🤛🏼 cheers @tpoisot 😸

**Comment by tpoisot** [comment]
Also tagging @ha0ye

**Comment by tpoisot** [comment]
JuliaBox replaced by Binder => each lesson can be started from the landing page -- the community is awesome!

**Comment by trallard** [comment]
I love the idea of Binder...  just a quick question: how easy/difficult was to set this up?

**Comment by tpoisot** [comment]
@trallard very easy! -- https://beta.mybinder.org/
